def ScriptAdviceOutlinePrompt(pre_storyline: str, characters: str, outline: str):
    prompt = [
        {
        "role": "system",
        "content": "You're an Editor who excels at providing insightful guidance to enhance the movie story outline crafted by the Writer.\nYour task is to offer advice on how to improve the existing story outline (<outline>) created by the Writer, taking into account the provided storyline (<storyline>) and characters (<characters>) of the story.\nWhen providing feedback, please focus on the following aspects of the outline:\n1. Evaluate whether the development of the story outline aligns harmoniously with the storyline and character introductions.\n2. Assess whether the contents of the story outline coherent, and whether there are any conflicts or poor transitions between plot points.\n3. Assess whether the outline adhere to logical consistency.\n4. Evaluate whether the outline makes up an interesting, engaging and thought-provoking story.\n5. Assess whether the outline has a clear ending.\n6. Other aspects you consider important.\nIf the content written by the Writer has issues in these aspects, you need to provide detailed revision suggestions for the problematic areas concisely.\nYour advice on how to improve the story outline (<outline>) should follow the format below:\n<advice>\nYour advice\n</advice>\nWhen you feel that there are no more revisions to be made to the current story outline, please reply only with <advice>None</advice>.\nStrictly obey this format and do not generate redundant content!"
        },
        {
        "role": "user",
        "content": f"Give advice on how to improve the initial version of the story outline (<outline>) written by the Writer based on the following storyline (<storyline>) and characters (<characters>):\n<storyline>\n{pre_storyline}\n</storyline>\n\n<characters>\n{characters}\n</characters>\nThe initial version of the story outline written by the Writer:\n<initial_outline>\n{outline}\n</initial_outline>\nYour advice on how to improve the story outline (<outline>) should follow the format below:\n<advice>\nYour advice\n</advice>\nWhen you feel that there are no more revisions to be made to the current story outline, please reply only with <advice>None</advice>.\nStrictly obey this format and do not generate redundant content!"
        }]
    return prompt